library(xtable);
library(tools);
library(lme4);


doAnova <- function(modelList){

    numberModels <- length(modelList);
    if(numberModels < 2 | numberModels > 9 )
      return;
    for(i in 1:numberModels){
        modelName <- paste("Model",i,sep="");
        assign(modelName,modelList[[i]]);
    }
    myAnova <- NULL;
    switch(as.character(numberModels),
      "2" = {myAnova <- anova(Model1,Model2)},
      "3" = {myAnova <- anova(Model1,Model2,Model3)},
      "4" = {myAnova <- anova(Model1,Model2,Model3,Model4)},
      "5" = {myAnova <- anova(Model1,Model2,Model3,Model4,Model5)},
      "6" = {myAnova <- anova(Model1,Model2,Model3,Model4,Model5,Model6)},
      "7" = {myAnova <- anova(Model1,Model2,Model3,Model4,Model5,Model6,Model7)},
      "8" = {myAnova <- anova(Model1,Model2,Model3,Model4,Model5,Model6,Model7,Model8)},
      "9" = {myAnova <- anova(Model1,Model2,Model3,Model4,Model5,Model6,Model7,Model8,Model9)}
    );

    Name <- rownames(myAnova);
    rownames(myAnova) <- NULL;

    myAnova[4] <- round(myAnova[4],3);
    myAnova[5] <- round(myAnova[5],3);
    myAnova[7] <- round(myAnova[7],3);

    myAnova <- cbind(Name,myAnova);
    return(myAnova);
}

generateReport <- function(myModelList){
    sink("tmpfile.tex");
    cat("\\documentclass{article} \n");
    cat("\\usepackage[final]{pdfpages} \n");
    cat("\\usepackage{graphicx} \n");
    cat("\\begin{document} \n");
    cat("\\title{lme4 Model Report} \n");
    cat("\\author{yeroon.net/lme4} \n");

    cat("\\maketitle \n");
    cat("\\begin{abstract} \n");
    cat("This document is automatically generated by the yeroon.net/lme4 web application. It shows an overview of all currently fitted models.\n");
    cat("\\end{abstract} \n");

    cat("\\section{Citations} \n");
    cat("If you have used lme4, please cite: \n");
    cat("\\begin{itemize}");

    cat("\\item Jeroen C.L. Ooms (2009). yeroon.net/lme4: A web interface for the R package lme4. Version 0.1.\n");
    cat("http://www.yeroon.net/lme4 \n");

    cat("\\item Douglas Bates and Martin Maechler (2009). lme4: Linear mixed-effects models using S4 classes. R package version 0.999375-31. \n");
    cat("http://CRAN.R-project.org/package=lme4");

    cat("\\end{itemize} \n");
    cat("Entries for latex users: \n");

    cat("\\begin{verbatim}  \n");
    cat("  @Manual{,   \n");
    cat("    title = {yeroon.net/lme4: A web interface for the R package lme4}, \n");
    cat("    author = {Jeroen C.L. Ooms}, \n");
    cat("    year = {2009}, \n");
    cat("    note = {Version 0.1},   \n");    
    cat("    url = {http://www.yeroon.net/lme4},  \n");
    cat("  }  \n");

    cat("\n");

    cat("  @Manual{,   \n");
    cat("    title = {lme4: Linear mixed-effects models using S4 classes}, \n");
    cat("    author = {Douglas Bates and Martin Maechler}, \n");
    cat("    year = {2009}, \n");
    cat("    note = {R package version 0.999375-31},   \n");
    cat("    url = {http://CRAN.R-project.org/package=lme4},  \n");
    cat("  }  \n");
    cat("\\end{verbatim}   \n");
    cat("\\newpage   \n");

    if(length(myModelList) > 1){

      try({
        myAnova <- doAnova(myModelList);
        cat("\\section{Analysis of Variance} \n");
        cat("Anova Table:\n");
        print(xtable(myAnova));
      });
    }

    cat("\\section{Models} \n");

    for(i in 1:length(myModelList)){

        cat("\\subsection*{Model",i,"}\n");
        thisModel <- myModelList[[i]];

        cat("\\subsubsection*{Model Formula} \n");
        cat("\\begin{verbatim}  \n");
        cat(attr(thisModel,"predictorString"));
        cat("\\end{verbatim}   \n");

        try({
            singleAnova <- anova(thisModel);
            cat("\\subsubsection*{Fixed Effects ANOVA} \n");
            cat("\\begin{verbatim}  \n");
            print(singleAnova);
            cat("\\end{verbatim}   \n");
        });

        cat("\\subsubsection*{Model Summary} \n");
        cat("\\begin{verbatim}  \n");
            print(thisModel);
        cat("\\end{verbatim}   \n");

        #cat("\\subsubsection*{Correlation of Fixed Effects} \n");
          myVcov <- as.matrix(vcov(thisModel));
          rownames(myVcov) <- names(fixef(thisModel));
          colnames(myVcov) <- names(fixef(thisModel));
          print(xtable(myVcov, caption=paste("Model",i,"Covariances of Fixed Effects")));
          print(xtable(cov2cor(myVcov), caption=paste("Model",i,"Correlation of Fixed Effects")));

        #cat("\\subsubsection*{Random Effects Matrices} \n");

        myVarCorr <- VarCorr(thisModel);
        for(j in 1:length(myVarCorr)){
          print(xtable(myVarCorr[[j]],caption=paste("Model",i,"Covariance of Random effects for",names(myVarCorr[j]))));
          print(xtable(cov2cor(myVarCorr[[j]]),caption=paste("Model",i,"Correlation of Random effects for",names(myVarCorr[j]))));
        }
        cat("\\clearpage \n");

        #### random effect plots ####

        sink();
        
        getRanef <- function(myModel){
          tryCatch(return(ranef(myModel,T)),error=function(e){return(ranef(myModel))});
        }

        myPlotRanef <- getRanef(thisModel);
        pdf(file="report.pdf", paper="a4r",width=11.67, height=8.27)
        
        for(i in 1:length(myPlotRanef)){
            print(dotplot(myPlotRanef,scales = list(x = list(relation = 'free')))[[i]]);
        }

        dev.off();
        sink("tmpfile.tex", append=TRUE);
        cat("\\includepdf[pages=-,landscape=true,fitpaper=true]{report.pdf}\n",sep="");
    }

    cat("\\end{document} \n");
    sink();
    texi2dvi("tmpfile.tex", texi2dvi="/usr/bin/texi2dvi", quiet=FALSE, pdf=TRUE);
   
}


generateReport(myModelList);